name: deploy stack
run-name: Deployment to ${{ inputs.environment }} by @${{ github.actor }} release ${{ github.ref_name }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        required: true
        options: [test, live]
      
      deploy:
        type: boolean
        description: deploy stack
        required: true
        default: true
      
      destroy:
        type: boolean
        description: destroy stack
        required: true
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: aws-actions/setup-sam@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - run: |
        chmod +x build.sh
        ./build.sh
    - run: sam build --use-container
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name stock-reminder-stack --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-${{ github.run_id }} --capabilities CAPABILITY_IAM --region eu-west-2